apiVersion: v1
kind: "List"
items:
- 
  apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      component: "squid"
    name: "squid-proxy"
  spec:
    ports:
      -
        port: 80
        targetPort: 8080
    selector:
      name: "squid"
      component: "squid"
-
  apiVersion: "v1"
  kind: "Route"
  metadata:
    name: squid-proxy
  spec:
    host: ""
    to:
      kind: "Service"
      name: "squid-proxy"
-
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    labels:
      name: "squid"
      component: "squid"
    name: "squid"
  spec:
    replicas: 1
    selector:
      component: "squid"
    template:
      metadata:
        labels:
          name: "squid"
          component: "squid"
      spec:
        serviceAccount: "squid"
        containers:
          -
            securityContext:
              runAsUser: 0
            env:
            -
              name: "PROXY_PEER"
              value: "${PROXY_PEER}"
            -
              name: "PROXY_PORT"
              value: "${PROXY_PORT}"
            image: "abutcher/squid"
            name: "squid"
            ports:
            -
              containerPort: 8080
              name: "http"
